services:
  sauron:
    build: .
    container_name: sauron
    restart: unless-stopped

    # Keep container interactive-friendly
    stdin_open: true
    tty: true

    # ROS networking (important if using multiple nodes/containers)
    network_mode: host

    # Hardware access (Sense HAT)
    privileged: true
    devices:
      - /dev/fb1
      - /dev/i2c-1
      - /dev/input
      - /dev/vchiq
      - /dev/dri
      # - /dev/video0
      # - /dev/media0
      # - /dev/media1
      # - /dev/v4l-subdev0
      # - /dev/v4l-subdev1
      # - /dev/dri

    # Match host permissions for input devices
    group_add:
      - input
      - video

    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=:0
      - XDG_RUNTIME_DIR=/tmp/runtime-ubuntu
      - QT_QPA_PLATFORM=xcb
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_OPENGL=software

    volumes:
      - /usr/lib/aarch64-linux-gnu/libcamera:/usr/lib/aarch64-linux-gnu/libcamera
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/runtime-ubuntu:/tmp/runtime-ubuntu

    command: ros2 launch launch/launch.py